/**
 * A service
 * has many offers (from different resellers)
 * - provider: the service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller.
 * e.g.: a concert. A provider just provides this event. Sellers - another organizations/websites, like best-tickets, aviasales and other retailers.
 * A service provider like a product manufacturer.
 * It's better to separate these concepts for all companies.
 * - service - IT development, payment - special services, like fl.ru
 */

'use strict';

const LocalBusiness = require('./local-business');
const CreativeWork = require('./creative-work');
const City = require('./city');

module.exports = {
  // May contain: type, provider, description, keywords
  name: { type: 'Text' },

  // GPC or Google Product Taxonomy
  category: { type: 'Text' },

  description: { type: 'Text' },

  provider: {
    type: 'Item',
    schema: 'LocalBusiness',
    ref: LocalBusiness
  },

  // The tangible thing generated by the service, e.g. a passport, permit, etc.
  serviceOutput: {
    type: 'ItemList',
    schema: 'CreativeWork',
    ref: CreativeWork,
    isHashMap: true
  },

  areaServed: {
    type: 'ItemList',
    ref: City,
    schema: 'City',
    isHashMap: true
  }

  // price is a less important than provider
  // offers: {
  //   type: 'ItemList',
  //   schema: 'Offer',
  //   ref: Offer,
  //   isHashMap: true
  // }

  // hasOfferCatalog: only for groups (segments, families, etc)
};
